### ISSUE TITLE
Performance bottleneck from "addTask"

### ISSUE THREAD

**Issue by etyp** [DHTMLX/meteor-gantt-data#5]
We're not directly using this package for our application, but have taken the same approach in setting up observers and mapping `added` messages to `addTask`.

We run into an issue where loading anything more than 20 or so tasks on first load can crash the browser because `addTask` calls `this.refreshData` every time. I'd imagine users of this package will experience the same thing.

Is there an option for not forcing `this.refreshData` on every `addTask` call?

See my comment here for more details: https://docs.dhtmlx.com/gantt/api__gantt_addtask.html

**Comment by gearcoded** [comment]
Answered here:
https://docs.dhtmlx.com/gantt/api__gantt_addtask.html#comment-3264508755
